server:
  port: 8084
feign:
  okhttp:
    enabled: true # 开启OKHttp功能
hm:
  db:
    database: hm-trade # 数据库名称
  swagger:
    title: "黑马商城交易服务"
    desc: "黑马商城交易服务"
    package: com.hm.trade.controller
